### ISSUE TITLE
all demos on website are reversed

### ISSUE THREAD

**Issue by esteinborn** [dangvanthanh/tipsy.sass#1]
On the website, all your tip demos are reversed.

North shows up in south:
![image](https://cloud.githubusercontent.com/assets/308007/3385160/66d18eaa-fc66-11e3-88b1-6d79486bf3e3.png)

South In North, etc etc
![image](https://cloud.githubusercontent.com/assets/308007/3385162/6f3ca426-fc66-11e3-958d-0a08025e58df.png)

**Comment by dangvanthanh** [comment]
@esteinborn Thank you very much. I will reversed tipsy of demo.
